# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Producto'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Venta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Almacen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='catalogo.Categoria', verbose_name='list of Categorias'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.UnidadMed'),
        ),
        migrations.AddField(
            model_name='compra',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Almacen'),
        ),
        migrations.AddField(
            model_name='compra',
            name='comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Proveedor'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
    ]
